### ISSUE TITLE
Print a warning in a case of unknown/ignored stuff

### ISSUE THREAD

**Issue by filip26** [filip26/alps#21]
**Is your feature request related to a problem? Please describe.**
An unknown content (attributes,elements) is silently ignored by a parser.

**Describe the solution you'd like**
A warning should be printed to a console.

**Comment by mamund** [comment]
i assume this is a behavior for the `validate` action, right? that's fine.

`transform` behavior on handling unknown content might need to be handled differently.

**Comment by filip26** [comment]
That's interesting, I was thinking about having a switch (`-vv`  or  `-w`) to enable printing of  warnings to a console no matter on the action (`validate` | `transform`).

Can you please help me understand your thoughts on `transform` in this context?

**Comment by mamund** [comment]
warnings for ignore and passed through vs. warnings for ignored and removed.

0) by default i'd like to "pass through" the unknown elements.
1) i also would prefer warnings for these cases and might even accept that as default (IOW, use `--silent` to supress warnings?)
2) would be happy to have a `--strict` and strips out all unknown elements as an option (a way to create a "clean" doc).
3) the `--strict` could bark errors for added properties for `validate` and drop the added properties for `transform` mode.

does this make sense?

**Comment by filip26** [comment]
yes, thanks for the input. I like the `--strict` and `--silent` switch idea.
