### ISSUE TITLE
Java 8: A JNI error has occurred

### ISSUE THREAD

**Issue by koriym** [filip26/alps#34]
A JNI error has occurred. The current [Download Java for Mac OS X](https://www.java.com/en/download/) page provides Java class file version 52.0 download but  your program compiled with version 55.0.

```
% alps.sh     
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/apicatalog/alps/cli/AlpsCommand has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by filip26** [comment]
Hi,
thank you for reporting it. The provided link leads to Java 8, but the current implementation requires Java 11 or greater. I'm not familiar with Mac OS X.  Does installation of Java 11 (preferably OpenJDK 11) on Mac OS X cause any issues?

**Comment by filip26** [comment]
here is a link to download [Oracle Java SE 11 (LTS)](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html). MacOS installer is included.

**Comment by koriym** [comment]
Thanks! Also, brew can install it. The problem is that the Java program announced  "Download Java for Mac OS X " page when Java is not installed.

**Comment by filip26** [comment]
got it, the `alps.sh` script should check what Java is installed and provide a download link instead of executing older Java version.
